version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "08:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(ci)"
