require:
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 5

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/EmptyMethod:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/Void:
  Enabled: false

RSpec:
  Language:
    Includes:
      Examples:
        - include_tests

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 6
Style/Documentation:
  Enabled: false
