name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v4
    - name: Build and publish gem
      uses: g2crowd/gh-actions/actions/publish-gem@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
